### ISSUE TITLE
Have you write a paper ?

### ISSUE THREAD

**Issue by zhangqianhui** [hvy/gan-resize-convolution#1]
Just a blog ?

**Comment by hvy** [comment]
Yup, just based on a blog post and no paper. I think it's an interesting idea so I wanted to see what actual difference it makes. As of today, I haven't seen it being used in any paper but according to the authors of the blog post, there will be one soon so let's stay tuned.

**Comment by 6o6o** [comment]
Same technique was used in multiple style transfer network published by Google in October https://arxiv.org/abs/1610.07629

**Comment by hvy** [comment]
You're right, thanks!
